### ISSUE TITLE
ENDBLOCK; not recognized

### ISSUE THREAD

**Issue by kleintom** [mjy/nexus_parser#10]
Based on a small sample size it's looking like morphobank's nexus files output `ENDBLOCK;` instead of `END;` to end blocks. Currently nexus_parser doesn't recognize `ENDBLOCK;` so those files fail to parse here:

https://github.com/mjy/nexus_parser/blob/6a647b32be6ec19a4bf7c07fed13bb35ae9f5743/lib/nexus_parser.rb#L272-L273
because they don't match `/end\;/i`

Is `ENDBLOCK;` something you want to support?

**Comment by mjy** [comment]
Sure, let's extend it, simply because I think we can extend the Token match quite easily.
