### ISSUE TITLE
Questions around Label and Number tokens in character state names

### ISSUE THREAD

**Issue by kleintom** [mjy/nexus_parser#16]
Pulled from issue 9:

There's a parse error on `60 'Iliac preacetabular process, length' /  subequal_to 25%_or_less_than`

the error occurs in `lexer#pop` where `next_token` is `%_or_less_than` and the error reported is

`expected NexusParser::Tokens::Number but received NexusParser::Tokens::RowVec at 61 'Mid dorsal (trunk) paramedian osteo...`

I think the issue in that particular case is that when we tokenize the string `25%_or_less_than` it tokenizes as the Tokens::Number `25` followed by the Tokens::Label `%_or_less_than`.  Mesquite imports that as you would expect, as the string `25% or less than` (in the ui at least Mesquite converts underscores to spaces).

If you can short circuit the discussion below please do so :-)

I noticed that, for unquoted strings, the only Tokens::Numbers that aren't Tokens::Labels are the ones that start with `-` (i.e. negative numbers). Then I wondered why couldn't a label start with a dash (currently it's required to start with `\w`, which includes `_` but not `-`).

So then I checked on what Mesquite does in that case:
* `-3e-12` gets imported as three states: `-`, `3e`, and `-12`.  This seems to be related to the following text from the glossary entry for `word` in the nexus spec: 
> A string of dark characters is broken into several words by whitespace and any punctuation other than brackets, unless the string is surrounded by quotes.

`-` is a punctuation character, so the first two state names make sense, the third does not (I would expect `-`, `12`).

If I change the name being imported to `-31e-12` then Mesquite gives me state names `-31e` and `-12`. Now I'm at a loss: in the previous example I could have thought it was trying to follow the spec (treating `-` as a punctuation symbol and not a negative sign), with maybe some error on not splitting correctly on the second `-`, but in this example it's not splitting either dash into its own, though it does split the entire string on the second dash...

If I simplify somewhat and give Mesquite the string `a-b-c` for a state name, that becomes `a`, `-`, `b`, `-`, `c`. nexus_parser interprets that as a single state name `a-b-c`.

Mesquite interprets `-a-b-c` as `-`, `a`, `-`, `b`, `-`, `c`, nexus_parser raises because that's neither a Number nor a Label (I think that's the problem).

**Comment by kleintom** [comment]
If I try to summarize, I think my questions at this point would be:
* What was the motivation for allowing character state names to be either `Label` or `Number`? Maybe because of the initial `-` noted above? (Maybe character state names need their own regex if something like that is the case?) Note that no matter which we tokenize as, the result is always saved as a string. FWIW the original nexus spec says
> Character and state names are single NEXUS words

As far as I can tell that seems to be how Mesquite treats what I give it (with some confusion noted above).

* Mesquite seems to follow that statement from the nexus spec on what a word is:
> A string of dark characters is broken into several words by whitespace and any punctuation other than brackets, unless the string is surrounded by quotes.

(see examples above) - should nexus_parser be doing the same here?

**Comment by mjy** [comment]
> What was the motivation for allowing character state names to be either Label or Number? Maybe because of the initial - noted above? 

IIRC because we see both in the wild.  Things like "Number of tarsomeres: 1 2 3" in addition to "Number of tarsomeres: one two three".   I honestly don't remember every dealing with the "-" in your examples, it's not ringing any bells, but the bells are very dusty.

>  should nexus_parser be doing the same here?

I think so. At first thought I think your observation "Maybe character state names need their own regex" is likely path forward.

**Comment by kleintom** [comment]
> > A string of dark characters is broken into several words by whitespace and any punctuation other than brackets, unless the string is surrounded by quotes.
> 
> (see examples above) - should nexus_parser be doing the same here?

I got a little in the weeds here, I'm not planning on working on that, mostly because I don't really understand the motivation for specifying names that way.
