### ISSUE TITLE
Multi-state codings of the form (01) with no space or comma silently drop the 1 state

### ISSUE THREAD

**Issue by kleintom** [mjy/nexus_parser#18]
If I import a matrix coding of the form `(01)`, it gets parsed as `@codings=[[#<NexusParser::NexusParser::Coding:0x00007fb957fc4b40 @notes=[], @states="0">]]` - I would expect that to be `@states=["0","1"]`.

Mesquite reads this as expected (as `0` and `1`), and if you import the `(01)` state Mesquite exports it as `(0 1)`, so this can be fixed by Mesquite (another one to announce on the readme?), but in that case it would be good to provide an error rather than silently dropping one of the states.

**Comment by kleintom** [comment]
The other related issue I was wondering about here is that Mesquite imports multistates of the form `{0 1}` as `0/1` in the ui - where `(0 1)` is represented as `0&1` - but it seems like TW and nexus_parser make no distinction, is that worth mentioning? I don't know how much the `{}` version is used and what the expectations around it are.

**Comment by mjy** [comment]
> but in that case it would be good to provide an error rather than silently dropping one of the states.

This only happens with leading zero I expect?  I.e. `14` is  ["14"], not ["1", "4"].  

I think your suggestion is fine, to error, particularly be cause Mesquite export does resolve it.

> {0 1} ... t seems like TW and nexus_parser make no distinction

You are right, TW doesn't distinguish AND/OR with multiple Observations.  More or less open-world in this regard.

**Comment by kleintom** [comment]
> This only happens with leading zero I expect? I.e. `14` is ["14"], not ["1", "4"].

I'm getting `14` and `124` both going to `@states="1"`, I'll see about throwing an error, thanks.
