### ISSUE TITLE
Repeats allowed in the TAXA list and CHARSTATELABELS lists

### ISSUE THREAD

**Issue by kleintom** [mjy/nexus_parser#7]
The original Nexus description reference seems to say that repeats aren't allowed in the taxa or character name lists:

* On p. 598 of the reference, `They [taxon names] must not correspond to another taxon name or number`
* On p. 602, `Character names must not correspond to another character name or number`

But nexus_parser allows both of those repeats. 

[I don't have a particular stand on this issue - it came up while doing TW work, but I think that work will be fine with or without this, I think. The result may look confusing in the ui though, with 0s and 1s meaning different things in different columns with the same name for example. And I'm not sure how repeated taxa makes sense in a matrix, unless repeated taxa rows have the same states, and then what's the point.]

I note the test file `test.nex` in the repository here: https://github.com/mjy/nexus_parser/blob/6a647b32be6ec19a4bf7c07fed13bb35ae9f5743/test/test.nex#L21 which says it was written by Mesquite (though maybe it's been altered since then), does have repeated character names, for example `Scape` is the character name of characters 28, 29, and 31.

**Comment by kleintom** [comment]
Here's a file with taxa and character name repeats:
```
#NEXUS

BEGIN TAXA;
  DIMENSIONS NTAX=2;
  TAXLABELS
    Argiope Argiope
  ;
END;

BEGIN CHARACTERS;
  DIMENSIONS NCHAR=2;
  FORMAT DATATYPE = STANDARD SYMBOLS = "01";
  CHARSTATELABELS
    1 shape / round square, 2 shape / elliptical rhomboid;

  MATRIX
  Argiope  01
  Argiope  10
;
END;
```

And here it is parsed:
```ruby
#<NexusParser::NexusParser:0x00007efee3084ce0
 @characters=
  [#<NexusParser::NexusParser::Character:0x00007efee3081f90
    @name="shape",
    @notes=[],
    @opt={:name=>"square", :label=>"1"},
    @states={"0"=>#<NexusParser::NexusParser::ChrState:0x00007efee31dccc8 @name="round">, "1"=>#<NexusParser::NexusParser::ChrState:0x00007efee31dcc78 @name="square">}>,
   #<NexusParser::NexusParser::Character:0x00007efee3081f40
    @name="shape",
    @notes=[],
    @opt={:name=>"rhomboid", :label=>"1"},
    @states={"0"=>#<NexusParser::NexusParser::ChrState:0x00007efee31db148 @name="elliptical">, "1"=>#<NexusParser::NexusParser::ChrState:0x00007efee31db0f8 @name="rhomboid">}>],
 @codings=
  [[#<NexusParser::NexusParser::Coding:0x00007efee31da590 @notes=[], @states="0">, #<NexusParser::NexusParser::Coding:0x00007efee31da450 @notes=[], @states="1">],
   [#<NexusParser::NexusParser::Coding:0x00007efee31d9870 @notes=[], @states="1">, #<NexusParser::NexusParser::Coding:0x00007efee31d9730 @notes=[], @states="0">]],
 @notes=[],
 @sets=[],
 @taxa=[#<NexusParser::NexusParser::Taxon:0x00007efee3220d10 @mesq_id="", @name="Argiope", @notes=[]>, #<NexusParser::NexusParser::Taxon:0x00007efee3220c70 @mesq_id="", @name="Argiope", @notes=[]>],
 @vars={:ntax=>"2", :nchar=>"2", :datatype=>"STANDARD", :symbols=>"01"}>
```

**Comment by mjy** [comment]
@kleintom For historical context the original Nexus reference has many issues that other standards like NeXML started to try to address.  These efforts had varying success, but overall were operational failures, i.e. their use and implementation in applications in the wild were largely not adopted.  

Implementation-wise I want to treat this as a functional/operational library based on the capabilities of Mesquite. I.e. if Mesquite can operate on the file (read, edit, return in a non-losey manner), then the format  is allowed.  

We may considering adding convenience methods here to validate against the  reference *if* they will be useful downstream (e.g. identifying data that needs to be handled at level 2 below).  Again though, I don't think we're trying to implement and validate the full standard, we're trying to be functional, so these kind of checks may be better off in the vendor/wrapping libraries.

This has consequences, as you anticipated for TaxonWorks import:

* Level 1 - When a label is duplicated then we will have simply flag and prevent import 
* Level 2 - Add a UI disambiguation that lets the user decide what to do with duplicate rows.

The initial TW implementation can be very strict, i.e. we only import data that can be unambiguously mapped to TW entities.  If it can't then it is skipped.

**Comment by kleintom** [comment]
Sounds good, thanks for the context.
