### ISSUE TITLE
CHARSTATELABELS with numeric state names parsed incorrectly?

### ISSUE THREAD

**Issue by kleintom** [mjy/nexus_parser#9]
There's other stuff going on but it looks like I'm seeing
`105 Chromosome_number_n /  18 17 16 15 14 13 12 ; ` parsed as
```
#<NexusParser::NexusParser::Character:0x00007f01c9f3aaf8
  @name="Chromosome_number_n",
  @notes=[],
  @opt={:name=>"", :label=>"5"},
  @states=
   {"0"=>#<NexusParser::NexusParser::ChrState:0x00007f01c877fa58 @name="18">,
    "1"=>#<NexusParser::NexusParser::ChrState:0x00007f01c877fa08 @name="16">,
    "2"=>#<NexusParser::NexusParser::ChrState:0x00007f01c877f9b8 @name="14">,
    "3"=>#<NexusParser::NexusParser::ChrState:0x00007f01c877f968 @name="12">,
    "4"=>#<NexusParser::NexusParser::ChrState:0x00007f01c8933638 @name="">,
    "5"=>#<NexusParser::NexusParser::ChrState:0x00007f01c9d7ab28 @name="">}>]
```
I can come back to this one later to make sure that's what's happening. A quick look at the code looks like number state names should be supported?

**Comment by mjy** [comment]
Good question.  This looks more like a quantitative character, I can't remember how we differentiate here. However in general, yes, numeric states should be handled and valid CharacterState labels in TW.

**Comment by mjy** [comment]
Note to self- were there limits to the number of states in the parser (IIRC there was re Paup?), i.e. where in the example above are 13, 15,  and what is name ="".

**Comment by kleintom** [comment]
Edit: moved this comment's discussion to issue 16.
